### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by SamHamamji** [ruberhg/GPU-Heaps#1]
Hello,

I just went over your paper and it seems to be interesting. I opened this repository to check the source code, but it seems to be missing. I could not find it, even in your commit history. Are you planning to release it?

**Comment by RaphaelFakhri** [comment]
indeed, can we look at the code? tx

**Comment by ruberhg** [comment]
Thanks for the notification. The source code has been uploaded.

**Comment by SamHamamji** [comment]
Great, thank you :+1:
